# database configs
spring.datasource.url=jdbc:mysql://localhost:5556/ServicoTecnico?serverTimezone=America/Sao_Paulo
spring.datasource.username=mysql
spring.datasource.password=mysql
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true

app.cors.allowed-origins=http://localhost:4200

spring.security.oauth2.authorizationserver.client.client-1.registration.client-id=client
spring.security.oauth2.authorizationserver.client.client-1.registration.client-secret={noop}secret
spring.security.oauth2.authorizationserver.client.client-1.registration.client-authentication-methods=client_secret_basic
spring.security.oauth2.authorizationserver.client.client-1.registration.authorization-grant-types=client_credentials
spring.security.oauth2.authorizationserver.client.client-1.registration.scopes=read
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/oauth2/jwks